# -*- coding: utf-8 -*-
"""115 Python Problems

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_92KjeITHJNyMKGOU0k_20rAtDQxAAPH
"""

#Basic Problems

#1. Variable Swap: Write a Python program to swap the values of two variables without using a temporary variable.

var1 = 5
var2 = 6

print("var1 = ", var1)
print("var2 = ", var2)

var1, var2 = var2, var1

print("After swap var1 = ", var1)
print("After swap var2 = ", var2)

#2. Even or Odd: Write a Python program that takes an integer as input and prints whether it is even or odd.

var3 = int(input("Enter the number: "))

if var3 % 2 == 0:
  print(var3 ,"is even number")
else:
  print(var3 ,"is odd number")

#3. String Reverse: Write a Python function to reverse a given string and return the reversed string.

def reversed_string(input_string):
  reversed_string = ""

  for char in input_string:
    reversed_string = char + reversed_string
  return reversed_string

original_string = "rifat"
reversed_string = reversed_string(original_string)
print(reversed_string)

#4. Type Conversion: Given a list of integers, write a Python program to convert each element of the list to a string.

li_1 = [9,12,7,4,6]
converted_string = []

for i in li_1:
  converted_string.append(str(i))
print(converted_string)

#5. Temperature Converter: Write a Python program that converts a temperature in Celsius to Fahrenheit. Take the Celsius temperature as input from the user

celsius = int(input("Enter the temperature in celsius: "))

fahrenheit = (celsius * 9/5) + 32

print("Temperature in celsius to fahrenheit: ", fahrenheit)

#6. Data Type Checker: Write a Python function that takes a variable as input and returns the data type of the variable as a string (e.g., “int”, “float”, “str”, “list”, etc.).

def data_type_checker(variable):
    data_type = type(variable).__name__
    return data_type

# Example usage:
var4 = 5
var5 = 3.14
var6 = "Hello, World!"
var7 = [1, 2, 3]

print("var4 is of type: ", f'"{data_type_checker(var4)}"')
print("var5 is of type: ", f'"{data_type_checker(var5)}"')
print("var6 is of type: ", f'"{data_type_checker(var6)}"')
print("var7 is of type: ", f'"{data_type_checker(var7)}"')

#7. String Palindrome: Write a Python function to check if a given string is a palindrome or not.

def palindrome(a):
  if a == a[::-1]:
    return a

str = "aabbcc"
result = palindrome(str)

if result:
  print("palindrome :", f'"{result}"')
else:
  print("Not palindrome")

#8. String Reversal with Slicing: Write a Python function to reverse a given string using slicing.

def revStr(a):
  return a[::-1]

str1 = "hello world"
print("reverse string using slicing: ", f'"{revStr(str1)}"')

#9. String Concatenation: Write a Python program that takes two strings as input and concatenates them into a single string without using the `+` operator

str2 = str(input("Enter first string: "))
str3 = str(input("Enter second string: "))

concat = " ".join([str2,str3])
print("After joining: ", concat)

# 10. Typecasting Challenge: Given three variables: `a = ‘100’`, `b = 25`, and `c = ‘10.5’`, write a Python program to perform the following operations and print the results:
# – Convert `a` to an integer and add it to `b`.
# – Convert `c` to a float and subtract it from the result of the first operation.
# – Convert the final result to a string and concatenate it with the string ” is the answer.”

a1 = "100"
b1 = 25
c1 = "10.5"

convert1 = int(a1) + b1
print("First Operation: ", convert1)

convert2 = float(c1) - convert1
print("Second Operation: ", convert2)

convert3 =" ".join([str(convert2), "is the answer"])
print(convert3)

# Python Conditional Statements:

# 11. Positive, Negative, or Zero: Write a Python program that takes a number as input and prints whether it is positive, negative, or zero.

num = int(input("Enter the number: "))
if num > 0:
  print("Positive")
elif num < 0:
  print("Negative")
elif num == 0:
  print("Zero")

# 12. Largest of Three Numbers: Write a Python program that takes three numbers as input and prints the largest among them.\

num2 = float(input("Enter 1st value "))
num3 = float(input("Enter 2nd value "))
num4 = float(input("Enter 3rd value "))

if num2 >= num3 and num2 >= num4:
    largest = num2
elif num3 >= num4 and num3 >= num2:
    largest = num3
else:
    largest = num4

print("The largest value is :", largest)

# 13. Leap Year Checker: Write a Python program that takes a year as input and determines if it is a leap year or not.

num5 = int(input("Enter the year :"))

if (num5 % 4 == 0 and num5 % 100 != 0) or (num5 % 400 == 0):
  print(num5 ," is a leap year")
else:
  print(num5 ," is not a leap year")

#14 Grades Classification: Write a Python program that takes a student’s percentage as input and prints their corresponding grade according to the following criteria:
# – 90% or above: A+
# – 80-89%: A
# – 70-79%: B
# – 60-69%: C
# – Below 60%: Fail

std_percentage = int(input('''
  Grading Classification:
  – 90% or above: A+
  – 80-89%: A
  – 70-79%: B
  – 60-69%: C
  – Below 60%: Fail

  Enter the percentage : '''))

if std_percentage >= 90 and std_percentage <=100:
  print("A+")
elif std_percentage >= 80 and std_percentage <= 89:
  print("A")
elif std_percentage >= 70 and std_percentage <= 79:
  print("B")
elif std_percentage >= 60 and std_percentage <= 69:
  print("C")
elif std_percentage >= 0 and std_percentage <= 59:
  print("Fail")
else:
  print("Please enter valid input")

# 15. Vowel or Consonant: Write a Python program that takes a single character as input and determines whether it is a vowel or a consonant.

str2 = str(input("Enter the character: "))

if (len(str2) == 1) and (str2.isalpha()):
  if str2 in "aeiou":
    print("This character is a vowel")
  else:
    print("This character is a consonent")
else:
  print("Enter valid character!")

# 16. Time Classification: Write a Python program that takes the time in hours (24-hour format) as input and prints “Good Morning”, “Good Afternoon”, “Good Evening”, or “Good Night” based on the time.

time = int(input("Enter the time in hours(24-hour format): "))

if 5 <= time <= 11:
  print("Good Morning")
elif 12 <= time <= 16:
  print("Good Afternoon")
elif 17 <= time <= 19:
  print("Good Evening")
elif 20 <= time <= 24:
  print("Good Morning")
else:
  print("Enter correct hour")

# 17. Triangle Type Checker: Write a Python program that takes three sides of a triangle as input and determines whether it forms an equilateral, isosceles, or scalene triangle.

side1 = float(input("Enter first side: "))
side2 = float(input("Enter second side: "))
side3 = float(input("Enter third side: "))

if (side1 + side2 > side3) and (side1 + side3 > side2) and (side2 + side3 > side1):
  if side1 == side2 == side3:
    print("Equilateral triangle")
  elif (side1 == side2 != side3) or (side1 == side3 != side2) or (side2 == side3 != side1):
    print("isosceles triangle")
  elif side1 != side2 != side3:
    print('scalene triangle')
else:
  print("It is not a triangle")

#18. Quadratic Equation Solver: Write a Python program that takes the coefficients (a, b, c) of a quadratic equation as input and calculates and prints the real roots (if they exist) or a message indicating the complex roots
import math

a = int(input("Enter the coef of a: "))
b = int(input("Enter the coef of b: "))
c = int(input("Enter the coef of c: "))

D = b**2 - 4*a*c

if D > 0:
  x1 = (-b + math.sqrt(b**2 - 4*a*c))/2*a
  x2 = (-b - math.sqrt(b**2 - 4*a*c))/2*a
  print("the real roots are: ", x1 ,"and ",x2)
elif D == 0:
    x1 = -b / (2*a)
    print("The real root is: x =", x1)
else:
  print("it has complex roots")

# 19. Number Ranges: Write a Python program that takes an integer as input and prints whether the number falls within the ranges: 0-50, 51-100, 101-150, or above 150

num6 = int(input("Enter an integer: "))

if num6 >= 0 and num6 <= 50:
    print("The number falls in the range 0-50.")
elif num6 >= 51 and num6 <= 100:
    print("The number falls in the range 51-100.")
elif num6 >= 101 and num6 <= 150:
    print("The number falls in the range 101-150.")
else:
    print("The number is above 150.")

